apiVersion : apps/v1
kind: Deployment
metadata:
  name: "myaks-4f15"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "myaks-4f15"
  template:
    metadata:
      labels:
        app: "myaks-4f15"
    spec:
      containers:
        - name: "myaks-4f15"
          image: "myakskuberegistry.azurecr.io/myaks"
          ports:
          - containerPort: 8080